title: Kosimizu Blog
email: you@example.com
description: >- 
  ポケモンニュースを中心に最新情報をお届けするブログ
baseurl: "" # サブディレクトリで使う場合は変更
url: "https://kosimizu.com"

# テーマ指定（GitHub Pages公式テーマ）
remote_theme: "pages-themes/minimal@v0.2.0"

# カスタムCSSを読み込む設定
sass:
  style: compressed

# 投稿設定
markdown: kramdown
kramdown:
  input: GFM
paginate: 5
